object_detection:
  build: .
  container_name: datascience
  restart: always
  environment:
     - TERM=xterm
  hostname: '127.0.0.1'
  ports:
     - "80:8888"
  volumes:
     - ./datascience:/root/datascience/